// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVoE-GHXrLyNYTjIAxwFALYa-Melr9K0U',
    appId: '1:846609336145:web:3d6b802d3c1aa691afb570',
    messagingSenderId: '846609336145',
    projectId: 'bornesan-daaf1',
    authDomain: 'bornesan-daaf1.firebaseapp.com',
    storageBucket: 'bornesan-daaf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEs1biooA386ZGKQxTmAAC6MXTCgDFbZo',
    appId: '1:846609336145:android:08d3e8496231d18dafb570',
    messagingSenderId: '846609336145',
    projectId: 'bornesan-daaf1',
    storageBucket: 'bornesan-daaf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2I5D6jzylZzc1lDP70Xjd9kgRs6hc6ok',
    appId: '1:846609336145:ios:f8bbac53d7485f99afb570',
    messagingSenderId: '846609336145',
    projectId: 'bornesan-daaf1',
    storageBucket: 'bornesan-daaf1.appspot.com',
    iosBundleId: 'com.example.bornesan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2I5D6jzylZzc1lDP70Xjd9kgRs6hc6ok',
    appId: '1:846609336145:ios:71e18ad563d6d145afb570',
    messagingSenderId: '846609336145',
    projectId: 'bornesan-daaf1',
    storageBucket: 'bornesan-daaf1.appspot.com',
    iosBundleId: 'com.example.bornesan.RunnerTests',
  );
}
